services:
  postgres:
    image: postgres:15-alpine
    container_name: legacybtc-pool-postgres
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./config/pool.env
    network_mode: host
    command: ["postgres", "-c", "listen_addresses=127.0.0.1", "-c", "port=5451"]
    volumes:
      - /srv/legacybtc-pool/postgres:/var/lib/postgresql/data
      - ./docker-init-db.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -p 5451 -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: legacybtc-pool-app
    restart: unless-stopped
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./config/pool.env
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
